# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(529, 539)
        self.btn_start = QtWidgets.QPushButton(Form)
        self.btn_start.setEnabled(True)
        self.btn_start.setGeometry(QtCore.QRect(270, 10, 121, 81))
        self.btn_start.setCheckable(False)
        self.btn_start.setAutoRepeat(False)
        self.btn_start.setAutoExclusive(False)
        self.btn_start.setObjectName("btn_start")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 251, 251))
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(270, 140, 113, 28))
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName("lineEdit")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(270, 200, 85, 28))
        self.spinBox.setObjectName("spinBox")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(270, 110, 88, 20))
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(280, 240, 171, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(280, 260, 171, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(280, 280, 171, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(280, 300, 171, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(280, 320, 171, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(280, 340, 171, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(280, 360, 171, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(280, 380, 171, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(280, 400, 171, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(280, 420, 171, 16))
        self.label_10.setObjectName("label_10")
        self.btn_get_plc_status = QtWidgets.QPushButton(Form)
        self.btn_get_plc_status.setEnabled(True)
        self.btn_get_plc_status.setGeometry(QtCore.QRect(400, 10, 121, 81))
        self.btn_get_plc_status.setCheckable(False)
        self.btn_get_plc_status.setAutoRepeat(False)
        self.btn_get_plc_status.setAutoExclusive(False)
        self.btn_get_plc_status.setObjectName("btn_get_plc_status")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_start.setWhatsThis(_translate("Form", "m9.2"))
        self.btn_start.setText(_translate("Form", "Start"))
        self.lineEdit.setWhatsThis(_translate("Form", "MW9, WORD"))
        self.lineEdit.setInputMask(_translate("Form", "DDD; "))
        self.spinBox.setWhatsThis(_translate("Form", "M9.1"))
        self.checkBox.setWhatsThis(_translate("Form", "M8.0real"))
        self.checkBox.setText(_translate("Form", "CheckBox"))
        self.label.setWhatsThis(_translate("Form", "DB100.dbw3"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.label_2.setWhatsThis(_translate("Form", "DB100.dbw5"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.label_3.setWhatsThis(_translate("Form", "DB100.dbw90"))
        self.label_3.setText(_translate("Form", "TextLabel"))
        self.label_4.setWhatsThis(_translate("Form", "DB100.dbw11"))
        self.label_4.setText(_translate("Form", "TextLabel"))
        self.label_5.setWhatsThis(_translate("Form", "DB103.dbw300"))
        self.label_5.setText(_translate("Form", "TextLabel"))
        self.label_6.setWhatsThis(_translate("Form", "DB103.dbw3"))
        self.label_6.setText(_translate("Form", "TextLabel"))
        self.label_7.setWhatsThis(_translate("Form", "mb90"))
        self.label_7.setText(_translate("Form", "TextLabel"))
        self.label_8.setWhatsThis(_translate("Form", "mb1"))
        self.label_8.setText(_translate("Form", "TextLabel"))
        self.label_9.setWhatsThis(_translate("Form", "I9.0"))
        self.label_9.setText(_translate("Form", "TextLabel"))
        self.label_10.setWhatsThis(_translate("Form", "qw9"))
        self.label_10.setText(_translate("Form", "TextLabel"))
        self.btn_get_plc_status.setWhatsThis(_translate("Form", "m9.2"))
        self.btn_get_plc_status.setText(_translate("Form", "Get PLC status"))

